/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthedSignUpRouteImport } from './routes/_authed/sign-up'
import { Route as AuthedSignInRouteImport } from './routes/_authed/sign-in'
import { Route as AuthedPasswordResetRouteImport } from './routes/_authed/password-reset'

const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthedSignUpRoute = AuthedSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedSignInRoute = AuthedSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedPasswordResetRoute = AuthedPasswordResetRouteImport.update({
  id: '/password-reset',
  path: '/password-reset',
  getParentRoute: () => AuthedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/password-reset': typeof AuthedPasswordResetRoute
  '/sign-in': typeof AuthedSignInRoute
  '/sign-up': typeof AuthedSignUpRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/password-reset': typeof AuthedPasswordResetRoute
  '/sign-in': typeof AuthedSignInRoute
  '/sign-up': typeof AuthedSignUpRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/_authed/password-reset': typeof AuthedPasswordResetRoute
  '/_authed/sign-in': typeof AuthedSignInRoute
  '/_authed/sign-up': typeof AuthedSignUpRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/password-reset' | '/sign-in' | '/sign-up' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/password-reset' | '/sign-in' | '/sign-up' | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_authed'
    | '/_authed/password-reset'
    | '/_authed/sign-in'
    | '/_authed/sign-up'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_authed/sign-up': {
      id: '/_authed/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthedSignUpRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/sign-in': {
      id: '/_authed/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthedSignInRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/password-reset': {
      id: '/_authed/password-reset'
      path: '/password-reset'
      fullPath: '/password-reset'
      preLoaderRoute: typeof AuthedPasswordResetRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthedRouteRouteChildren {
  AuthedPasswordResetRoute: typeof AuthedPasswordResetRoute
  AuthedSignInRoute: typeof AuthedSignInRoute
  AuthedSignUpRoute: typeof AuthedSignUpRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedPasswordResetRoute: AuthedPasswordResetRoute,
  AuthedSignInRoute: AuthedSignInRoute,
  AuthedSignUpRoute: AuthedSignUpRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
